language: python
os: linux
arch:
 - amd64
 - ppc64le
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install codecov
    - pip install -r dev-requirements.txt
    - pip install -e .

script:
    - make test

after_success:
  - codecov

notifications:
    email: false
